# Generated by Django 5.0.3 on 2024-04-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=78, unique=True)),
                ('server', models.CharField(max_length=4)),
                ('summoner_name', models.CharField(max_length=16)),
                ('summoner_tag', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAdditionalInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summoners.player')),
                ('summoner_id', models.CharField(max_length=63)),
                ('account_id', models.CharField(max_length=56)),
                ('level', models.PositiveIntegerField()),
                ('summoner_icon', models.PositiveIntegerField()),
            ],
        ),
    ]
