# Generated by Django 5.0.3 on 2024-03-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_player_puuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeradditionalinfo',
            name='id',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerAdditionalInfo',
        ),
    ]
